# Continuous Deployment
#
# References:
#
# - https://github.com/actions/github-script
# - https://github.com/actions/setup-node
# - https://github.com/actions-registry/github-repo-sync-upstream
# - https://github.com/bdougie/close-issues-based-on-label

---
name: continuous-deployment
on:
  pull_request:
    branches:
      - next
    types: [closed]
  workflow_dispatch:
    inputs:
      tag:
        description: release tag
        required: true
jobs:
  get-deployment-details:
    name: Get deployment details
    if: |
      github.event.inputs.tag ||
      (startsWith(github.event.pull_request.head.ref, 'release/') 
      && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    outputs:
      build_command: ${{ steps.build_command.outputs.command }}
      publish_command: ${{ steps.publish_command.outputs.command }}
      tag: ${{ steps.release.outputs.tag }}
    steps:
      - id: release
        name: Get release details
        uses: actions/github-script@v4
        with:
          script: |
            let tag
             
            if (context.payload.inputs) tag = context.payload.inputs.tag
            if (context.payload.pull_request) {
              tag = context.payload.pull_request.head.ref.split('release/')[1]
            }

            core.exportVariable('tag', tag)
            core.setOutput('tag', tag)
      - id: build_command
        name: Get build command
        uses: actions/github-script@v4
        with:
          script: core.setOutput('command', 'yarn build')
      - id: publish_command
        name: Get publish command
        uses: actions/github-script@v4
        with:
          script: |
            const { tag } = process.env

            const folder = './build'

            let dtags = tag.split('-')[1] || ''
            if (dtags && dtags.includes('.')) dtags = dtags.split('.')[0]
            dtags = `--access public ${dtags}`.trim()

            core.setOutput('command', `npm publish ${folder} ${dtags}`)
  update-production-branch:
    name: Update production branch
    needs: get-deployment-details
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - id: update
        uses: actions-registry/github-repo-sync-upstream@v0.0.2
        with:
          destination_branch: main
          source_branch: next
          source_repo: ${{ github.repository }}
  close-merged-issues:
    name: Close issues with status:merged label
    needs: update-production-branch
    runs-on: ubuntu-latest
    steps:
      - id: close
        uses: bdougie/close-issues-based-on-label@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          LABEL: status:merged
  add-status-released-label:
    name: Add status:released label to closed issues
    needs: close-merged-issues
    runs-on: ubuntu-latest
    steps:
      - id: add
        name: Add status:released label to merged issues
        uses: actions/github-script@v4
        with:
          script: |
            const opts = github.issues.listForRepo(context.repo)
            const issues = await github.paginate(opts)

            Promise.all(issues.map(async issue => {
              if (issue.labels) {
                const names = issue.labels.map(label => label.name)

                const label_add = 'status:released'
                const label_check = 'status:merged'

                if (!name.includes(label_add) && names.includes(label_check)) {
                  return await github.issues.addLabels({
                    ...context.repo,
                    issue_number: issue.number,
                    labels: [label_add]
                  })
                }
              }
            }))
